### ISSUE TITLE
formScene.fxml

### ISSUE THREAD

**Issue by kirubel-web** [kirubel-web/Student_Managment#9]
line 14 what happend?

javafx.fxml.LoadException: 
/home/k/.config/Code/User/workspaceStorage/79d532aff0b41ecd536b214d998d6194/redhat.java/jdt_ws/Student_Managment_7eb95efe/bin/formScene.fxml:14

**Comment by HenokNegatu** [comment]
remove the constructor

**Comment by kirubel-web** [comment]
i thought it was because of the initialization method. Thanks
